version: '3'
services:
  author:
    build:
      context: .
      dockerfile: Dockerfile-author
    ports:
      - 4502:4502
    links:
      - publisher:publisher
      # - solr:solr
  publisher:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    ports:
      - 4503:4503
    # links:
    #   - solr:solr
  # solr:
  #   image: solr
  #   ports:
  #     - 8983:8983
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - elevate_dam