FROM openjdk:8

MAINTAINER sharpslinger

RUN apt-get update && apt-get install netcat -y

# Copy over files
COPY aem/ /aem/

WORKDIR /aem

# unpack, then install
RUN java -Xmx2048m -Xms1024m -XX:MaxPermSize=1024m -jar aem-quickstart-6.1.jar -unpack -r nosamplecontent
RUN chmod +x /aem/install-aem.sh /aem/finalize-author.sh
RUN /aem/install-aem.sh author

EXPOSE 4502 8000
ENTRYPOINT ["/aem/crx-quickstart/bin/quickstart"]

